---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: aks-flux-lab04-2
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: aks-flux-lab04
  url: ssh://git@github.com/namtran091/aks-flux-lab04
